import React from "react";

const locale = {

	PRIORTIYLEVEL:"Öncelik Seviyesi",
	TOPICOFREQUEST:"Talep Konusu",
	DETAIL:"Detay",
	UPLOAD:"YÜKLE",
	SUBMIT:"ONAYLA",
	EMAILTEXTBOX:"Lütfen talep içeriğini giriniz.",
	SEND:"GÖNDER",
	DESCRIPTION:"Açıklama",
	TYPE:"Destek Türü",
	FILENAME:"Dosya Adı",
	RESPONSE:"Yanıt",
	CLOSE:"KAPAT",
	SAVE:"KAYDET",
	LOW:"Düşük",
	MEDIUM:"Normal",
	HIGH:"Yüksek",
	CLIENT:"Müşteri",
	NONE:"Yok",
	BUSINESSNAME:"Şirket İsmi",
	SUPPORTPAGE:"Destek Sayfası",
	CREATEDATETIME:"Oluşturma Tarihi",
	STATUS:"Durum",
	NEWCLIENT: "Kullanıcı ve Müşteri için Yeni Client",
	COMPANYAPPLICATIONERROR:"Bu sayfaya girmeden önce lütfen başvurunuzu tamamlayınız. Tamamladıysanız, Lütfen tekrar giriş yapınız.",
	WAIT:'Lütfen bekleyiniz . Destek Talebiniz gönderiliyor ...',

	OTHER: "Diğerleri",
	LETTERS: "Mektuplar",
	DOCUMENTS: "Dökümanlar",
	VISA: "Vize",
	TAX: "Vergi",
	VAT: "Vat",
	PAYROLL: "Maşş Bordrosu",
	YEAREND: "Yıl Sonu",
	TECHNICALISSUES:"Teknik sorunlar",
	EMAIL:"E-Posta",

	CURRENCYNULLERROR:'Lütfen Birim seçiniz',
	INVOICENULLERROR:'Lütfen Fatura Tipi Seçiniz',
	PHOTONULLERROR:'Lütfen Fatura Fotoğrafı Seçiniz',
	EXPENSES:'Giderler',
	INVOICEDATE:'Fatura Tarihi',
	INVOICEENDDATE:'Fatura Bitiş Tarihi',
	CLEAR:'Temizle',
	AMOUNT:'Miktar',
	SELECTCURRENCY:'Lütfen Birim Seçiniz',
	INVOICETYPE:'Fatura Tipi',
	EXPORTXLS:'XLS İndir',
	UPLOADINVOICEPHOTO:'Fatura Fotoğrafı yükle',
	FILTERINFORMATION:'filtre için tarih seçiniz',
	NEGATIVEVALUEERROR:'Lütfen pozitif miktar giriniz',
	REQUESTSENDING: "İsteğiniz Gönderiliyor",
	DONE:'Onaylandı',
	INPROGRESS:'Devam Etmekte',
	REJECTED:'Reddedildi',
	PENDING:'Beklemede',
	INCOMES:'Gelirler',
	INCOMEDATE:'Gelir Tarihi',
	INCOMEENDDATE:'Bitiş Tarihi',
	DELETEREQUEST:'Silme İsteği',
	//**
	//**
};

export default locale;